# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 217b050f53298f1665abdad1a9ce46ba3b833f712b96124ced292952066be560352f39be32ed8e66d50cb54103a4dfdcdde71bf3bb05edbf617b88f2308bca57

test:
  secret_key_base: f1240637f7d9477fdf00cbec4d6a1f82d248415d8ad1e96ccb8beb18e7a77df57a0051c2e784a8cd30c735580f1393c1dd919da0e1da867091945afec1f0d1f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
